/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: ['intro', 'fundamentals', 'accessibility', 'installation'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'components/button', 
        'components/carousel', 
        'components/chip', 
        'components/home-button', 
        'components/keypad', 
        'components/mnemonic-box', 
        'components/mnemonic-quiz', 
        'components/modal', 
        'components/pagination'
      ],
      collapsed: false,
    },
  ],
};

module.exports = sidebars;
